// Code generated by protoc-gen-go.
// source: example.proto
// DO NOT EDIT!

/*
Package example is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	Test
*/
package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Test struct {
	Label            *string `protobuf:"bytes,1,req,name=Label" json:"Label,omitempty"`
	Number           *int32  `protobuf:"varint,2,req,name=Number" json:"Number,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Test) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func (m *Test) GetNumber() int32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func init() {
	proto.RegisterType((*Test)(nil), "example.Test")
}

var fileDescriptor0 = []byte{
	// 81 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x54, 0xb9,
	0x58, 0x42, 0x52, 0x8b, 0x4b, 0x84, 0x78, 0xb9, 0x58, 0x7d, 0x12, 0x93, 0x52, 0x73, 0x24, 0x18,
	0x15, 0x98, 0x34, 0x38, 0x85, 0xf8, 0xb8, 0xd8, 0xfc, 0x4a, 0x73, 0x93, 0x52, 0x8b, 0x24, 0x98,
	0x80, 0x7c, 0x56, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x4a, 0x61, 0xd6, 0x3f, 0x00, 0x00,
	0x00,
}
